<!DOCTYPE html>
<html>
<head>
    <title>Student Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #2c3e50;
            margin-bottom: 10px;
        }
        .student-info {
            margin-bottom: 30px;
        }
        .info-row {
            margin-bottom: 15px;
        }
        .label {
            font-weight: bold;
            width: 150px;
            display: inline-block;
        }
        .value {
            display: inline-block;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
        .timestamp {
            margin-top: 20px;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Student Report</h1>
        <p>Generated on {{ date('d/m/Y H:i:s') }}</p>
    </div>

    <div class="student-info">
        <div class="info-row">
            <span class="label">Enrollment No:</span>
            <span class="value">{{ $student->enrollment_no }}</span>
        </div>
        <div class="info-row">
            <span class="label">Name:</span>
            <span class="value">{{ $student->first_name }} {{ $student->last_name }}</span>
        </div>
        <div class="info-row">
            <span class="label">Email:</span>
            <span class="value">{{ $student->email }}</span>
        </div>
        <div class="info-row">
            <span class="label">Birth Date:</span>
            <span class="value">{{ $student->birthdate }}</span>
        </div>
        <div class="info-row">
            <span class="label">Semester:</span>
            <span class="value">{{ $student->sem }}</span>
        </div>
    </div>

    <div class="footer">
        <p>This is an official student report generated by the Time Table Management System.</p>
        <div class="timestamp">Document ID: {{ uniqid() }}</div>
    </div>
</body>
</html> 